name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Update package-lock.json
        run: npm install --package-lock-only --ignore-scripts

      - name: Commit package-lock.json if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          git diff --quiet && git diff --staged --quiet || git commit -m "ci(release): update package-lock.json"
          git push

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment to release to NPM
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
